### ISSUE TITLE
Support for Ecto 2.0

### ISSUE THREAD

**Issue by bgeihsgt** [danielberkompas/cloak#10]
Ecto 2.0 is in RC right now and should be releasing soon. Cloak is pinned to Ecto 1.1 right now. It'd be great to have Cloak support for 2.0 given we want to move our app to 2.0 soon. Thanks!

**Comment by Mrjaco12** [comment]
I did a brief look and I don't think that cloak is actually dependent on any ecto < 2.0 features so it *should* just be a matter of updating the dependency.

**Comment by danielberkompas** [comment]
@bgeihsgt @Mrjaco12 Doesn't the `{:ecto, ">= 1.0.0"}` version requirement cover Ecto 2.0 already? Since Cloak doesn't require any Ecto 2.0 features, I don't want to prevent people from using it if they are on Ecto 1.

**Comment by Mrjaco12** [comment]
When I tried it locally it didn't work by default with ecto2-rc but maybe the version checker ignores rc/beta versions?

**Comment by danielberkompas** [comment]
Yeah, possibly. I think it will work once `rc` is out of the version name. In the meantime, you can use the `override` option in your deps.

```elixir
{:ecto, "~> 2.0.0-rc3", override: true}
```
