### ISSUE TITLE
Cloak relies in deprecated :crypto API that will be removed in OTP 24

### ISSUE THREAD

**Issue by v0idpwn** [danielberkompas/cloak#102]
We are getting close to OTP 24 and I think this issue should be addressed.

**Comment by danielberkompas** [comment]
I'd happily accept a PR for this if you're able.

**Comment by v0idpwn** [comment]
Sure, will do it :)

Shall we keep support for OTP 21? We can dinamically select API based on the running version.

**Comment by danielberkompas** [comment]
Yes please. That's the main reason this hasn't been done yet.

**Comment by wingyplus** [comment]
Do we need to have elixir and otp job matrix in semaphore ci to test against the old version and incoming version?

**Comment by v0idpwn** [comment]
I think this would be the best with the decision to maintain compatibility with 21, @wingyplus. 

Personally, I'd break compatibility with OTP 21. [Even rebar doesn't support it anymore](https://github.com/erlang/rebar3/pull/2555), and users that plan to stick to it could just not update Cloak. This would also allow to use Persistent Term instead of ETS as vault (The current vault implementation isn't really a bottleneck, but it seems like the correct decision).

**Comment by wingyplus** [comment]
I have been try in https://github.com/wingyplus/cloak/blob/ci-matrix/.semaphore/semaphore.yml. I will open a PR if maintainer is ok to have it. :)

During setup, I found that Elixir 1.12 is require OTP version 22+ (refer to https://wingyplus.semaphoreci.com/jobs/5c15f396-a07b-41eb-958b-ba22e912ce31).

**Comment by danielberkompas** [comment]
This is fixed in #104!
