### ISSUE TITLE
Clock with changeset issue 

### ISSUE THREAD

**Issue by santoshturamari** [danielberkompas/cloak#115]
Hi All,

I am using Cloak 0.6.2 version. It was working all good. I upgraded the Elixir version to Elixir 1.13.0, Phoenix - 1.5.9 and phoenix_pubsub : 2.0.
After upgrading, I am getting the following error

(exit) an exception was raised:
** (UndefinedFunctionError) function Cloak.EncryptedBinaryField.equal?/2 is undefined or private
(cloak 0.6.2) Cloak.EncryptedBinaryField.equal?(nil, “Basement Flat, 2 Barons Court Road”)
(ecto 3.7.2) lib/ecto/changeset.ex:576: Ecto.Changeset.cast_field/8
I am passing the changeset in this way
struct

|> cast(
  upcase(params, [:current_address_postcode]),
  ~w[
         current_address_street current_address_locality current_address_county
         current_address_postcode current_address_udprn
       ]a
)
It was working all good previously, now it is throwing error.
Any help to fix this, would be highly appreciated.

Thanks,
Santosh T

**Comment by danielberkompas** [comment]
@santoshturamari You should upgrade to a more recent version of Cloak. You are using an old version with a newer version of Ecto (3.7.2). The newer version of Ecto requires a new `equal?` function to be defined on custom Ecto types. 

More recent versions of Cloak implement this `equal?` function.

**Comment by santoshturamari** [comment]
@danielberkompas  Thanks for the reply.
I am facing some issue with existing encrypted data in our databases which has been encrypted by the older version of Cloak.
It throws compatibility error, when I try to upgrade the cloak version.
