### ISSUE TITLE
Issue integration with Ecto2?

### ISSUE THREAD

**Issue by erneestoc** [danielberkompas/cloak#12]
I'm attempting to use this library, followed instructions, and even read the encrypt fun inside the cipher derectory..  I keep getting this error.
```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (crypto) :crypto.aes_ctr_stream_encrypt({:error, <<46, 220, 70, 162, 202, 119, 143, 51, 77, 116, 51, 201, 103, 43, 123, 112>>, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 0}, "arggraarggra")
        (crypto) crypto.erl:1376: :crypto.do_stream_encrypt/2
        lib/cloak/ciphers/aes_ctr.ex:115: Cloak.AES.CTR.encrypt/2
        lib/cloak.ex:141: Cloak.encrypt/1
        lib/ecto/encrypted_binary_field.ex:12: Cloak.EncryptedBinaryField.dump/1
        (ecto) lib/ecto/type.ex:641: Ecto.Type.do_adapter_dump/3
        (ecto) lib/ecto/repo/schema.ex:595: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:608: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5

```
What am I doing wrong?

**Comment by philss** [comment]
@erneestoc it's probably related to the key that you are using. How did you generate the key?

Try to generate your key like this:

```elixir
:crypto.strong_rand_bytes(32) |> Base.encode64
```

This will generate a base64 string that you can use as your key:

```
config :cloak, Cloak.AES.CTR,
  tag: "AES",
  default: true,
  keys: [
    %{
      tag: <<1>>,
      key: :base64.decode("YOUR BASE64 KEY HERE"),
      default: true
    }
  ]
```

More info in this issue: #5 .

**Comment by philss** [comment]
did you try to generate another key, @erneestoc?

**Comment by rpelyush** [comment]
@philss I had the same issue with key.
This ```:crypto.strong_rand_bytes(32) |> Base.encode64``` helped, thanks!
How about adding this as an example to README? https://github.com/danielberkompas/cloak/pull/14

**Comment by philss** [comment]
@rpelyush I agree with that. cc/ @danielberkompas

**Comment by danielberkompas** [comment]
The documentation has been updated in #14, thanks to @rpelyush. Closing this down. :smile:
