### ISSUE TITLE
mix cloak.migrate doesn't update encryption_version field

### ISSUE THREAD

**Issue by bgeihsgt** [danielberkompas/cloak#16]
I just ran a cloak.migrate on my production system and it successfully updated each encrypted column, but it did not update the encryption_version column on any of the rows.

I think the culprit is in https://github.com/danielberkompas/cloak/blob/master/lib/mix/tasks/cloak.migrate.ex#L120-L126. The old code used to automatically set the encryption version field, but now that no longer happens, this task needs to explicitly update that param before the call to repo.update!

There's also a warning firing for calling update directly on the struct. I think the right fix is to create a changeset that gets passed to update!

I would do this, but I don't have the time right now to create and test the fix.

**Comment by danielberkompas** [comment]
Yeah, this is a side effect of upgrading Cloak for Ecto 2.0.  Cloak used to rely on schema callbacks to update the version, so `repo.update!` was enough. Now, it's going to need to explicitly update the version field.

**Comment by nathany** [comment]
Hi Daniel. Any update on Ecto 2 support?

**Comment by danielberkompas** [comment]
@nathany Cloak should already support Ecto 2.0, apart from this bug.
