### ISSUE TITLE
instructions to cloak plain text fields

### ISSUE THREAD

**Issue by nathany** [danielberkompas/cloak#17]
I want to cloak a few fields in an existing schema before it goes into production. Any recommendations for migrating plain text `string` fields to encrypted `binary` fields?

**Comment by nathany** [comment]
I have the part to convert to/from binary fields in Postgres. Now just need to encrypt them.

```elixir
defp encode(table, column) do
  # USING is necessary to explicitly covert the column from string to binary.
  execute ~s"""
    ALTER TABLE #{table}
    ALTER #{column} TYPE bytea USING #{column}::bytea;
  """
end

defp decode(table, column) do
  alter table(table) do
    modify column, :string
  end

  # decode binary data back to plain text.
  execute ~s"""
    UPDATE #{table}
    SET #{column} = convert_from(#{column}::bytea, 'utf8');
  """
end
```

**Comment by nathany** [comment]
Current issue:
```
No cipher found to decrypt "plaintext"
```

**Comment by danielberkompas** [comment]
This is a valid issue. I don't have a solution for you yet but I will work on it.

**Comment by nathany** [comment]
So I now have binary (bytea) fields containing plain text, but I still need to encrypt them.

Using `github: "danielberkompas/cloak"`, the  `mix cloak.migrate` task reports:

```
[info] 0 records found needing migration
```

Not a surprise, as `encryption_version` is nil and there isn't anything setup to handle plain text in the config.

**Comment by danielberkompas** [comment]
I'm thinking that the best way to solve this would be to add a Cloak configuration option.

```elixir
config :cloak, raise_on_decrypt: false
```

If you set it to `false`, Cloak will just read out the value of a field if it can't decrypt it. This should work fine for plaintext fields. Then, when the struct is saved next, Cloak would encrypt it.

**Comment by nathany** [comment]
That could work, assuming the fields have already been converted to binary (in my case they have).

I am thinking of writing a migration to encrypt all the existing fields as well -- using a regular Ecto migration (instead of `cloak:migrate`).

**Comment by tielur** [comment]
@nathany did you have any luck with this? I'm currently going down something similar. I wrote a migration that creates new binary fields, and then updates them with the string fields.

```elixir
patients = Repo.all(Patient)
    Enum.each(patients, fn(patient) ->
      changeset = Patient.changeset(patient, %{first_name_binary: Cloak.encrypt(patient.first_name), last_name_binary: Cloak.encrypt(patient.last_name), email_binary: Cloak.encrypt(patient.email)})
      Repo.update!(changeset)
    end)
```

I've noticed that when I query the database, the values are still showing as binary. How would I be able to treat them as a string?

**Comment by nathany** [comment]
Sorry, I don't recall. It's been a while since I've used Elixir.

**Comment by danielberkompas** [comment]
@tielur can you share your schema module's `schema` definition?

**Comment by tielur** [comment]
@danielberkompas I think I found out how to do it. Basically what I'm doing is using the `encode` and `decode` functions that @nathany wrote above. I'm changing the field type from `utf8` to `bytea`. Once that is done I'm reading all of the rows, updating the fields I changed the type of, and saving them so they get encrypted via Cloak.

**Comment by danielberkompas** [comment]
Gonna merge this discussion with #29.
