### ISSUE TITLE
cloak migration not running

### ISSUE THREAD

**Issue by nathany** [danielberkompas/cloak#18]
It gives the following error:

```
❯ mix cloak.migrate

15:28:58.377 [info]  === Starting Migration ===
** (FunctionClauseError) no function clause matching in Mix.Tasks.Cloak.Migrate.validate!/2
    lib/mix/tasks/cloak.migrate.ex:82: Mix.Tasks.Cloak.Migrate.validate!(nil, [])
    lib/mix/tasks/cloak.migrate.ex:77: Mix.Tasks.Cloak.Migrate.parse/1
    lib/mix/tasks/cloak.migrate.ex:57: Mix.Tasks.Cloak.Migrate.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Erlang 19.0.2, Elixir 1.3.2, ecto 2.0.4

I do have `config :cloak, :migration` setup and `Application.get_env(:cloak, :migration)` returns the data I expect when ran in iex.

**Comment by danielberkompas** [comment]
@nathany This has been fixed on master. See https://github.com/danielberkompas/cloak/pull/15 for more details. Once I get a couple more issues fixed, I'll push a new release.

**Comment by nathany** [comment]
Thanks. I'll update to master and test it tomorrow.

**Comment by nathany** [comment]
Thanks for the fix.
