### ISSUE TITLE
How to encrypt with user's own key instead of key from config?

### ISSUE THREAD

**Issue by seymores** [danielberkompas/cloak#24]
Assume the user has his own key, and assuming it is just to figure out how to inject the user's key into Cloak's private [cipher](https://github.com/danielberkompas/cloak/blob/master/lib/cloak.ex#L195) function.

Any idea how to get the user's key from current active process? :-)

**Comment by danielberkompas** [comment]
Since there's no guarantee that the casting will occur in the same process, I'm not sure this is possible using Ecto Types. You'll probably need to implement this in your application logic before the data hits Ecto.
