### ISSUE TITLE
Add salt option to cloak for increased security

### ISSUE THREAD

**Issue by cayblood** [danielberkompas/cloak#26]
It would be nice if you could specify a salt column that could be used to encrypt each row's cloak-enabled columns differently, for added security.

**Comment by tomciopp** [comment]
@cayblood Typically a salt is only used for hashing a one way function. AES encryption uses a random initialization vector which it stores along with the data when it encrypts it. Therefore it should not be necessary, nor would it add any additional security if there was an additional salt field.

@danielberkompas Unless you have any other views on this topic I suggest this issue should be closed.

**Comment by danielberkompas** [comment]
I agree with @tomciopp. This idea would also be difficult to implement because it requires two fields. Cloak (and Ecto custom types in general) work best on a single field.
