### ISSUE TITLE
Allow key to be in Application env

### ISSUE THREAD

**Issue by tielur** [danielberkompas/cloak#31]
I'm currently working on a project where I am pulling the Cloak cipher encryption key down from AWS KMS at runtime and storing the decrypted data key in the app's env. Right now Cloak supports pulling the key from the System environment but it would be nice if it also handled pulling from the OTP app env.

**Comment by tielur** [comment]
👍 
@danielberkompas When will the new push to hex.pm occur?

**Comment by danielberkompas** [comment]
I just released `0.3.2` with this change.
