### ISSUE TITLE
Cloak.AES.CTR `encrypt/2` not explicitly called?

### ISSUE THREAD

**Issue by asummers** [danielberkompas/cloak#38]
It appears `encrypt/2` in `AES` cipher will always default to the `\\ nil` case in the second parameter, as the code currently exists. Was this intended to be used for something? If so, it should be added to the behaviour, as the behaviour only specifies `encrypt/1` which doesn't play nicely when you `@impl` it for Elixir 1.5 (it complains about you `@impl`ing the arity 2 function). If not, it and the associated tests should be removed. Or is the intention to be able to specify key versions when you're encrypting at the `Cloak.encrypt` level? If so, how do you envision that API of being able to (now) specify cipher tag and potentially key tag? Could be converted to a keyword list for arguments, and I can adjust the ciphertext tag to be an opt.  So it'd look something like:

```
Cloak.encrypt("plaintext", cipher_tag: "AES", key_tag: <<1>>)
```

Willing to put in the work here, just not sure what you were envisioning :)  My inclination is that being able to specify the key tag would be more powerful. I can see reasons why that would be undesirable to be able to set un application code, though sane defaults of always taking the one with `default: true` would alleviate many of those arguments.

**Comment by danielberkompas** [comment]
It's been a while since I wrote that so I don't know what the original intention was. Not all ciphers will necessarily use key tags, so I don't think the answer is to add the `key_tag` parameter to `encrypt/1`.

Probably the right answer is just to remove it.

**Comment by asummers** [comment]
I have a branch that does the non-removal part if you'd like to take a peek at how it would work.  It's been a little while since I looked at this code, so I would have to rethink how it would work the way you said. 

https://github.com/danielberkompas/cloak/compare/master...asummers:fix-behaviour
