### ISSUE TITLE
** (MatchError) no match of right hand side value: false

### ISSUE THREAD

**Issue by r-donoghue** [danielberkompas/cloak#40]
** (Mix.Config.LoadError) could not load config config/config.exs
    ** (MatchError) no match of right hand side value: false
    (stdlib) base64.erl:212: :base64.decode_binary/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:776: :erl_eval.eval_map_fields/5
    (stdlib) erl_eval.erl:259: :erl_eval.expr/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:236: :erl_eval.expr/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5

Appears when attempting to run mix deps.get

Installed Elixir version:
Erlang/OTP 20 [erts-9.0] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]
Elixir 1.5.2

Raw Code:
`use Mix.Config

config :myapp,
  ecto_repos: [Myapp.Repo]
  
config :cloak, Cloak.AES.CTR,
  tag: "AES",
  default: true,
  keys: [
    %{tag: <<1>>, key: :base64.decode("your key here"), default: true}
  ]

config :myapp, Myapp.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "N0kBJVG1Q8d4w5ddkQUzwsJiCA/f4VnVVz1aMOcOwmxUZCVgTv9KUunnFHzxIV/Q",
  render_errors: [view: Myapp.ErrorView, accepts: ~w(html json)],
  pubsub: [name: Myapp.PubSub,
           adapter: Phoenix.PubSub.PG2]

config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

import_config "#{Mix.env}.exs"
`

**Comment by danielberkompas** [comment]
You need to put an actual key in the "your key here" section.

```
%{tag: <<1>>, key: :base64.decode("your key here"), default: true}
```

You can generate a key like so:

```
$ iex
iex> 32 |> :crypto.strong_rand_bytes() |> Base.encode64()
```

Copy the resulting string into "your key here".
