### ISSUE TITLE
Migrations in multi tenant applications

### ISSUE THREAD

**Issue by tomciopp** [danielberkompas/cloak#43]
I have an application with multiple schema based tenants however the current mix task does not allow for prefixes to be passed through. I've written another migration task for my own app but have run into issues surrounding `Cloak.Config.all` hardcoding the atoms `:migration`, and `:included_applications`. I think a better solution would be to add a boolean field that should be checked when defining configuration to mark whether we are defining a cipher. This way we avoid hardcoding specific fields, and follows the pattern defined by `default_cipher`

**Comment by danielberkompas** [comment]
@tomciopp sorry for the late response here. Would it be enough to just add a `prefix` option to the configuration, so that you could do:

```elixir
      config :cloak, :migration,
        repo: MyApp.Repo,
        prefixes: [...],
        models: [{MyApp.Model1, :encryption_version},
                 {MyApp.Model2, :encryption_version}]
```

**Comment by tomciopp** [comment]
It may take a few days since I am on vacation. Will take a look at it when
I get back

**Comment by danielberkompas** [comment]
We could use the `__info__/1` reflection function on modules to decide whether a module is a cipher instead of hard-coding `:migration` and `:included_applications`.

```
Cloak.AES.GCM.__info__(:attributes)
# => [vsn: [223319134436500479424408323018685985178], behaviour: [Cloak.Cipher]]

Cloak.Cipher in Cloak.AES.GCM.__info__(:attributes)[:behaviour]
# => true
```

**Comment by tomciopp** [comment]
I'm wary of adding a `prefix` key unless we convert Cloak to the callback style of configuration that is favored in Phoenix and other libraries. I'm assuming most applications will be loading prefixes from a database and if you have multiple tenants this is likely to be a function call. (Ex. `MyApp.Tenant.prefixes()`) In my experience executing code in the configuration just doesn't work when you want to deploy to prod. I do like checking the `__info__` function. I will see if I can put together a PR for that sometime soon.

**Comment by danielberkompas** [comment]
Does using `__info__/1` solve this issue or is there more that should be done?

**Comment by tomciopp** [comment]
Using `__info__` helps a lot. Perhaps there should be some docs for people who need to handle multi-tenancy however I am unsure if it is necessary. I think we can mark this as closed
