### ISSUE TITLE
Is poison optional?

### ISSUE THREAD

**Issue by jdewar** [danielberkompas/cloak#59]
I ran into `** (Mix) Could not start application poison: could not find application file: poison.app`

Adding it as an application seems to be in opposition with its 'optional' nature in the mix.exs:

```
  def application do
    [applications: [:poison, :logger]]
  end

  defp deps do
    [
      {:ecto, ">= 1.0.0"},
      {:poison, ">= 1.5.0", optional: true},
```

It would be nice if it was truly optional, as I probably only need to encode strings

**Comment by danielberkompas** [comment]
Yes, it should be truly optional as long as you don't need to encode maps. I removed it from the `applications` list.
