### ISSUE TITLE
(Postgrex.Error) ERROR 22021 (character_not_in_repertoire)

### ISSUE THREAD

**Issue by kiere** [danielberkompas/cloak#65]
I'm trying to integrate Cloak into a new Elixir/Phoenix application:
Elixir 1.6.4
Phoenix 1.3.0
Ecto 2.2.8
Postgrex 0.13.5
PostgreSQL 10.0 (postgres.app v2.1.3 (42) on macOS 10.12.6)

I have added the following config to my `dev.secret.exs`:
```Elixir
# 256-bit Key Generation...
# 32 |> :crypto.strong_rand_bytes() |> Base.encode64()
config :cloak, Cloak.AES.GCM,
  default: true,
  tag: "GCM",
  keys: [
    %{tag: <<1>>, key: Base.decode64!("AhBXnRHXxioy+OBaZXP1dawhvhtNFwTzi9kh9QBkXuQ="), default: true}
  ]
```
_(That's not the real key, but it was generated the same way using the comment above the config)_

In my `User` schema, I have the following...
```Elixir
@primary_key {:id, :binary_id, autogenerate: true}
@foreign_key_type :binary_id
schema "users" do
  field :first_name, :string
  field :last_name, :string
  field :email, Cloak.EncryptedBinaryField
  field :password, :string, virtual: true
  field :encrypted_password, :string
  field :role_id, :integer

  timestamps()
end
```

In `iex -S mix`, I am using the following to create a new user...
```Elixir
u = %{first_name: "John", last_name: "Doe", email: "jdoe@example.org", role_id: 1, password: "testtesttest"}
Access.create_user(u)  # uses a registration changes
```

The error happens immediately after I press Return...
```Elixir
[debug] QUERY ERROR db=6.1ms queue=0.1ms
INSERT INTO "users" ("email","encrypted_password","first_name","last_name","role_id","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) [<<71,67, 77, 1, 1, 1, 155, 236, 178, 69, 217, 4, 85, 199, 200, 109, 212, 173, 52, 157, 189, 169, 155, 50, 46, 131, 75, 64, 125, 254, 84, 118, 204, 44, 213, 176, 24, 87, 56, 111, 81, 135, 124, 245, 239, 61, 69, 176, 119, ...>>, "$2b$12$7MI5LjhnwLha9h8ajMQTRu3xeOT6f68mShQMq3B62/cSBbYLuIKwu", "John", "Doe", 99, {{2018, 4,24}, {16, 30, 44, 267127}}, {{2018, 4, 24}, {16, 30, 44, 269435}}, <<121, 250, 94, 219, 67, 204, 64, 150, 155, 119, 116, 212, 150, 119, 23, 133>>]
** (Postgrex.Error) ERROR 22021 (character_not_in_repertoire): invalid byte sequence for encoding "UTF8": 0x9b
    (ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
    (ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
```

As soon as I disable Cloak (by removing `Cloak.EncryptedBinaryField` from the schema and reverting to `:string`, everything works as expected (with the exception of the `encryption_version` field being blank, for obvious reasons).

Is there anything different that needs to be done to the underlying database field?  Or do we need to add anything else to the `User` module besides altering the `schema`?  I read through these documents and followed them...

https://hexdocs.pm/cloak/Cloak.html#content
https://hexdocs.pm/cloak/Cloak.AES.GCM.html#content
https://github.com/danielberkompas/cloak/issues/5 (How to generate keys?)

**Comment by danielberkompas** [comment]
As noted in the EncryptedBinaryField documentation, the underlying field type must be of type `:binary`. This is because the Ecto type will generate a binary that is not UTF-8 encoded. Postgres's varchar field is UTF-8 encoded.

Also, please note that there are major changes coming to Cloak in 0.7.0-alpha.1. https://github.com/danielberkompas/cloak/releases/tag/v0.7.0-alpha.1

If you're starting a new integration, I recommend you base it off that version, as 0.7.0 will be released _very_ soon. (This week)

**Comment by kiere** [comment]
Hi @danielberkompas, thanks for the quick response!  A quick change to the db  solved the issue, however, is this the documentation you were referring to?
https://hexdocs.pm/cloak/Cloak.EncryptedBinaryField.html#content

I didn't see anything that specifically said you cannot use a `:string` data type when creating the table via a migration.  (However, my field was pre-existing anyway.)

> An Ecto.Type to encrypt a binary field.

Since strings in Elixir are binaries, I missed the distinction.

I think this page (usually found first) may be the source of my confusion.
https://hexdocs.pm/cloak/Cloak.html#module-ecto-integration

The use of `:string`/`:binary` under the **Ecto Type** makes it seem like your db field can be either a `:string` or a `:binary`.

Would you be opposed to me writing up a Wiki page for "Getting Started" from the newcomers perspective.  Something that stitches all this together a little more smoothly.  I felt like I was jumping around a bit too much to get Cloak setup fully.

**Comment by danielberkompas** [comment]
You're right, the docs on `EncryptedBinaryField` don't mention this, though the other `Encrypted` fields do.

If you would like, you can look at updating the guides in the `guides/` folder, as these will be packaged up in the Hex documentation and be accessible to everyone. However, I can also do this and would be happy to in preparation for the 0.7.0 release.

**Comment by kiere** [comment]
PS - Anyone finding this later, the docs/guides for 0.7.0+ are excellent for getting started.  Just rewrote everything using them and it worked perfectly the first time.
