### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by danielberkompas** [danielberkompas/cloak#66]
- [x] Release 0.7.0

## 1.0

- [ ] Split Ecto components into `cloak_ecto` library. `Vault` and `Cipher` would remain in `Cloak`, while `Cloak.Field.*` and `mix cloak.migrate` would move to `cloak_ecto`.

**Comment by beardedeagle** [comment]
Would the split make it easier to add support for something like using cloak with mnesia without ecto?

**Comment by danielberkompas** [comment]
It wouldn't make it _easier_ per se, but it would allow you to depend on the Cloak core without bringing in a bunch of Ecto modules you won't use.

**Comment by danielberkompas** [comment]
Closing this issue in favor of having separate issues and milestones for the roadmap.
