### ISSUE TITLE
convert Cloak errors into Ecto errors

### ISSUE THREAD

**Issue by jaimeiniesta** [danielberkompas/cloak#74]
I have a Phoenix 1.3.3 app using Cloak 0.7.0, on Ecto 2.2.10 over MySql 5.7.

To make it work, I needed to change the type of the columns from `:string` to `:binary`. Which in turn uses the `blob` MySQL type.

OK, this is working fine but then I released the app where the DB structure was old, and it had `varchar(255)` instead of `blob`. When I tried the app there, encryption failed but it didn't convert the Cloak error into an Ecto.Changeset error as I would have expected. Instead, it converted the value to `:error` and saved it to DB.

Is there a way to ensure that, if encryption fails, the error is converted to a changeset error? It should do this when there is an error in the vault but also if there's an error in the DB. Or maybe the error wasn't catched and the `:error` value comes later when reading it and trying to decode it?

I can provide a sample app to reproduce this, if needed.

**Comment by jaimeiniesta** [comment]
After further investigation, this error was not due to the column type in MySQL.

It keeps failing but unfortunately I can't tell why. I'll close this issue by now.

**Comment by danielberkompas** [comment]
I’d be interested in the sample app if you are still willing to share it. This does sound like something that could be improved.

**Comment by jaimeiniesta** [comment]
Sorry but I can't reproduce it. This app works fine in local releases but fails when deployed, not sure why. I'll share it with you if I can reproduce it fully.

**Comment by jaimeiniesta** [comment]
So I finally found what caused the bug. It was due to a bad encoding in the MySQL DB used in the server, it was incorrectly set to `latin1` instead of the expected `utf8`.

So, encryption was OK, but when it saved it (to a `binary` column, `BLOB` in MySQL), it was stored in another charset and later when it is read from the DB, it cannot be decrypted.

I'm not sure this can be detected from Cloak, this seems probably related to https://github.com/xerions/mariaex/issues/116

**Comment by danielberkompas** [comment]
Does encoding matter in MySQL blobs? It seems to me that binary blobs should just be just that, a blob of binary, with no opinion on encodings.

**Comment by jaimeiniesta** [comment]
Well I don't know what exactly caused this, but it seems related to the issue I linked above. These are the steps I took:

1.- Created a Phoenix app, using MySQL with MariaEx.
2.- Configured Cloak for it. The encrypted columns need to be of type `:binary`, not `:string`.
3.- Everything works fine locally.
4.- Deployed it to another server where the DB had not been created via `mix ecto.setup`, but loading a dump from my development DB where I forgot to include the charset (`utf8`), so that it was created as `latin1`. That is, I made the dump with `mysqldump my_app_dev` where I should have used `mysqldump --databases my_app_dev`.
5.- Now, the deployed app doesn't work fine because when a value is inserted there, it gets garbled somehow, and when it's later read, it cannot be decrypted.

I tried to make it without Cloak, following [this post](https://github.com/dwyl/phoenix-ecto-encryption-example), and I got the same error. The problem is in the DB. Here are some logs from that attempt:

These errors show how when the record is loaded, it cannot be decrypted (for the previous values)
```
10:25:00.543 [info] POST /admin/stores/1
LOAD: value: <<80, 21, 63, 101, 107, 63, 63, 26, 63, 3, 74, 63, 98, 63, 63, 63, 89, 41, 63,
  13, 63, 34, 12, 102, 80, 63, 63, 63, 70, 52, 64, 63, 63>>
LOAD: decrypted: :error
LOAD: value: <<33, 38, 75, 63, 63, 88, 71, 63, 72, 63, 63, 63, 63, 63, 36, 63, 63, 93, 63,
  63, 24, 96, 102, 35, 48, 120, 63, 53, 63, 63, 62, 63, 10, 63, 13, 56>>
LOAD: decrypted: :error
```

Then, we encrypt the new values `some / secret`. As you see `AES.encrypt` does its job fine:

```
DUMP: value: "some"
DUMP: to_string: "some"
DUMP: AES.encrypt: <<47, 226, 195, 21, 128, 200, 145, 155, 208, 127, 205, 144, 96, 38, 236, 178,
  219, 157, 77, 9, 12, 241, 153, 241, 190, 194, 244, 25, 89, 19, 200, 154, 210,
  193, 37, 147>>
DUMP: value: "secret"
DUMP: to_string: "secret"
DUMP: AES.encrypt: <<42, 43, 63, 77, 149, 43, 34, 200, 197, 5, 59, 49, 52, 190, 235, 87, 37, 139,
  87, 188, 146, 7, 255, 109, 10, 240, 161, 139, 81, 246, 166, 196, 21, 120, 3,
  244, 11, 75>>
```

Proof that encryption works fine:

```elixir
iex(my_app@127.0.0.1)5> AES.decrypt(<<47, 226, 195, 21, 128, 200, 145, 155, 208, 127, 205, 144, 96, 38, 236, 178,
...(my_app@127.0.0.1)5>   219, 157, 77, 9, 12, 241, 153, 241, 190, 194, 244, 25, 89, 19, 200, 154, 210,
...(my_app@127.0.0.1)5>   193, 37, 147>>)
"some"
iex(my_app@127.0.0.1)6> AES.decrypt(<<42, 43, 63, 77, 149, 43, 34, 200, 197, 5, 59, 49, 52, 190, 235, 87, 37, 139,
...(my_app@127.0.0.1)6>   87, 188, 146, 7, 255, 109, 10, 240, 161, 139, 81, 246, 166, 196, 21, 120, 3,
...(my_app@127.0.0.1)6>   244, 11, 75>>)
"secret"
```

Now we get redirected to the store, so it's loaded from the DB. But this time, the stored values are different, so we get a decryption error:

```
10:25:00.570 [info] Sent 302 in 27ms
10:25:00.649 [info] GET /admin/stores/1
LOAD: value: <<47, 63, 63, 21, 63, 63, 63, 63, 127, 63, 96, 38, 63, 63, 63, 77, 9, 12, 63,
  63, 63, 63, 63, 63, 25, 89, 19, 63, 63, 63, 37, 63>>
LOAD: decrypted: :error
LOAD: value: <<42, 43, 63, 77, 63, 43, 34, 63, 63, 5, 59, 49, 52, 63, 63, 87, 37, 63, 87, 63,
  63, 7, 63, 109, 10, 63, 63, 63, 81, 63, 63, 63, 21, 120, 3, 63, 11, 75>>
LOAD: decrypted: :error
10:25:00.655 [info] Sent 200 in 5ms
```

I hope this helps! The problem does not seem to be in Cloak, but due to a misconfiguration on the DB charset when working with MariaEx.

**Comment by danielberkompas** [comment]
Thanks for the detailed write up! I agree, this doesn’t look like a problem with Cloak.
