### ISSUE TITLE
:system AES keys aren't getting base64 decoded

### ISSUE THREAD

**Issue by bgeihsgt** [danielberkompas/cloak#9]
I'm running `0.2.0` and noticed that when specifying an AES key from an environment variable, Cloak is not base64 decoding the value retrieved from `System.get_env`. Is this by design? 

I think it should base 64 decode the contents of the environment variable as that's the key that I would expect to be used given I base64 encoded the key when I set the environment variable.

**Comment by philss** [comment]
I can to take this one if you agree, @danielberkompas.

**Comment by danielberkompas** [comment]
Why can't you just set the environment variable to the base64 encoded key?

**Comment by danielberkompas** [comment]
@philss go for it.

**Comment by bgeihsgt** [comment]
@philss There's an issue with this approach in that it breaks existing data that was saved the old way. I don't want to update to latest Cloak because I'll lose data that was saved with the old way. We're probably going to need a new handler that's called something different than system.

**Comment by danielberkompas** [comment]
@bgeihsgt Can you elaborate on how it breaks existing data? This is just about how you store your keys in environment variables. Previously, if you used the `{:system, "ENV_VAR_NAME"}` syntax, ENV_VAR_NAME had to store the key in binary. I'm not even sure that's possible.

Now, ENV_VAR_NAME should be a base64 encoded string, which should be easy to store. I don't see how this causes a problem?

**Comment by bgeihsgt** [comment]
Here's what happens before the fix:

- Generated a key
- Base 64 encoded the key
- Set the base 64 encoded value as an ENV variable in my production environment

The code before the fix will read the base 64 encoded value and use that as the key. So the encrypted values saved in the database are encrypted with the base 64 string, not the key itself.

If we leave the fix as is, then the code will try and decrypt the values using the real key instead of the base 64 string. This would not work as they were encrypted using the base 64 value.

So I'm proposing we update the above fix to define a new name instead of `system` (maybe `env`?) Then I add a new key that properly base64 decodes. In a later release we could then remove `system` as an option.

**Comment by danielberkompas** [comment]
I'm honestly pretty surprised that the `:crypto` module (which Cloak.Ciphers.AES uses under the hood) would accept a Base64 encoded string rather than a binary key.

The `{:system, "VAR_NAME"}` syntax is an Elixir standard, so I don't want to eliminate it in favor of something like `{:env, "VAR_NAME"}`. Fortunately, there should be an easy fix here.

Configure two keys in Cloak, like this:

```
config :cloak, Cloak.AES.CTR,
        default: true,
        tag: "AES",
        keys: [
          %{tag: <<1>>, key: System.get_env("ENV_VAR"), default: false},
          %{tag: <<2>>, key: {:system, "ENV_VAR"}, default: true}
        ]
```

Then run `mix cloak.migrate` to migrate all your data to the new `{:system, "ENV_VAR"}`-powered key. Cloak will read your data using the non-decoded key, and will write it again using the decoded key.

**Comment by danielberkompas** [comment]
When I try to use a base64 encoded string with `:crypto`, I get an argument error:

```
:crypto.aes_ctr_stream_encrypt({"eJg25UXy7jesebHc1qfRMMkow8dQSaaLdGkYwTDkSRg=", <<112, 182, 104, 48, 149, 111, 63, 103, 38, 222, 161, 168, 16, 65, 96, 211>>, <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 0}, "Hello world")
    crypto.erl:1376: :crypto.do_stream_encrypt/2
```

I don't see how your data could have been encrypted with the base64 string. It has to be decoded to binary first. Can you share your configuration?

**Comment by danielberkompas** [comment]
Closing this down due to inactivity. I'll be happen to reopen once my question about configuration above can be answered. :smile:
