### ISSUE TITLE
Outstanding work for 1.0?

### ISSUE THREAD

**Issue by svileng** [danielberkompas/cloak#91]
Thank you for your work on this @danielberkompas!

I'm considering using cloak in a production environment and noticed the latest release is an `alpha`.

I checked the issues/PRs/projects in the repo and it I couldn't see anything important left to release a `1.0` stable version.

Do you see any breaking changes coming up and when do you think `1.0` would be released? I just want to make sure we're making the right decision here and don't waste time in migrations later on.

Thank you!

**Comment by danielberkompas** [comment]
@svileng Thanks!  There are no planned improvements before releasing 1.0.0. I've only waited this long between the alpha and full release to give time for bugs to be discovered.

**Comment by svileng** [comment]
@danielberkompas Thank you for the quick response and for letting me know 👍  It sounds to me that the current version is more of a "release candidate" rather than an "alpha" i.e. `1.0.0-rc.0`. To me, an alpha is something experimental and unstable, so that's why I was cautious to use in production ([wikipedia](https://en.wikipedia.org/wiki/Software_release_life_cycle#Stages_of_development)). It's something to consider next time you carve out a release 🙏

**Comment by andrejsm** [comment]
Any updates on how close we are to the v1?

**Comment by danielberkompas** [comment]
1.0.0 has been released, as of now!
