### ISSUE TITLE
MyApp.Vault.encrypt("plaintext") failing

### ISSUE THREAD

**Issue by beardedeagle** [danielberkompas/cloak#92]
I'm getting the following error on `1.0.0-alpha` when following the docs:
```
** (ArgumentError) argument error
    (crypto) crypto.erl:797: :crypto.block_encrypt/4
    (cloak) lib/cloak/ciphers/aes_gcm.ex:44: Cloak.Ciphers.AES.GCM.encrypt/2
```
Reading the crypto docs (http://erlang.org/doc/man/crypto.html#block_encrypt-4), I'm wondering if this is the issue:
```
block_encrypt(aes_gcm | aes_ccm, Key, Ivec, {AAD, PlainText, TagLength}) -> {CipherText, CipherTag} | Error
```
It also appears that this is the old api?
```
Don't use this function for new programs! Use the new api.
```
OTP: 22.0.1 (compiled with kerl)
Elixir: 1.8.2 (compiled with kiex against OTP target)
Cloak: 1.0.0-alpha.0

**Comment by danielberkompas** [comment]
I don't think this is due to the `block_encrypt` function. More likely, it has to do with your key not being available or base64 decoded?

**Comment by beardedeagle** [comment]
I think it's due to OTP 22 personally, as there as a lot of changes around the crypto libs. I ended up rolling my own module internally that mostly mimics yours and it works fine with `TagLength` added:
```
  def encrypt(val) do
    ivec = :crypto.strong_rand_bytes(16)

    {ciphertext, ciphertag} =
      :crypto.block_encrypt(
        :aes_gcm,
        :base64.decode(System.get_env("VAULT_KEY")),
        ivec,
        {"AES256GCM", to_string(val), 16}
      )

    ivec <> ciphertag <> ciphertext
  end
```

**Comment by danielberkompas** [comment]
I guess that could be the case, if OTP 22 introduces breaking changes to the `:crypto` module. I'd be a bit surprised if that's the case, but I haven't been keeping up with changes to OTP lately.

**Comment by danielberkompas** [comment]
I pushed up a commit to test the library on Travis against OTP 22, and I'm not seeing any deprecation warnings or errors: https://travis-ci.org/danielberkompas/cloak/builds/539769955

**Comment by beardedeagle** [comment]
Interesting, I'll dig further as I'm sure I'll use this library in another project I'm working on

**Comment by praveenperera** [comment]
+1 same issue with OTP 22

**Comment by stocks29** [comment]
In case anyone else stumbles across this, the key in the config needs to be decoded bytes, not base64 encoded string:

https://github.com/danielberkompas/cloak/blob/master/config/test.exs#L8

```elixir
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=")},
```
